//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unbe.Mathematics.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unbe.Mathematics.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		/// &lt;summary&gt;{4} converts a single {2} value to a {0} vector by {1}assigning it to every component.&lt;/summary&gt;
        ///		/// &lt;param name=&quot;v&quot;&gt;{2} to convert to {0}&lt;/param&gt;
        ///		/// &lt;returns&gt;Converted value.&lt;/returns&gt;
        ///		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        ///		public static {3} operator {0}({2} v) {{ return new {0}(v); }}
        ///.
        /// </summary>
        internal static string SingleToVectorOperator {
            get {
                return ResourceManager.GetString("SingleToVectorOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    /// &lt;summary&gt;{0} zero value.&lt;/summary&gt;
        ///    public static readonly {0} zero;
        ///
        ///    /// &lt;summary&gt;x component of the vector.&lt;/summary&gt;
        ///    public {1} x { readonly get { return value[0]; } set { this.value = this.value.WithElement(0, value); } }
        ///    /// &lt;summary&gt;y component of the vector.&lt;/summary&gt;
        ///    public {1} y { readonly get { return value[1]; } set { this.value = this.value.WithElement(1, value); } }
        ///    /// &lt;summary&gt;z component of the vector.&lt;/summary&gt;
        ///    public {1} z { readonly get { retur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vector4Props {
            get {
                return ResourceManager.GetString("Vector4Props", resourceCulture);
            }
        }
    }
}
